const items = [
    {
        id: '001',
        image: '1.jpg',
        company: 'H&M',
        item_name: 'Night Suit for Women',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Sep 2025',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: '2.jpg',
        company: 'AS FASHION',
        item_name: 'Skirt for Women',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Sep 2025',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: '3.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Sep 2025',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: '4.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Sep 2025',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: '5.jpg',
        company: 'TITAN',
        item_name: 'Casual Watch for Men',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Sep 2025',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: '6.jpg',
        company: 'NOISE',
        item_name: 'Smart Watch for Men & Women',
        original_price: 1495,
        current_price: 1495,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Sep 2025',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: '7.jpg',
        company: 'The Indian',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        delivery_date: '10 Sep 2025',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: '8.jpg',
        company: 'APPLE',
        item_name: 'I phone 16 Light Green Color',
        original_price: 67285,
        current_price: 67285,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Sep 2025',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
      id: '009',
      image: '9.webp',
      company: 'FAIR & LOVELY',
      item_name: 'Fairness Cream for Women',
      original_price: 199,
      current_price: 199,
      discount_percentage: 0,
      return_period: 10,
      delivery_date: '10 Sep 2025',
      rating:{
        stars: 3.9,
        count: 4567,
      },
    },
    {
      id: '10',
      image: '10.webp',
      company: 'GARNIER',
      item_name: 'Vitamin C Serum for Both Men & Women',
      original_price: 485,
      current_price: 485,
      discount_percentage: 0,
      return_period: 10,
      delivery_date: '10 Sep 2025',
      rating:{
        stars: 4.9,
        count: 1597,
      },
    },
    {
      id: '11',
      image: '11.webp',
      company: 'MAMA EARTH',
      item_name: 'Face Scrub',
      original_price: 658,
      current_price: 658,
      discount_percentage: 0,
      return_period: 10,
      delivery_date: '10 Sep 2025',
      rating:{
        stars: 4.7,
        count: 4516,
      },
    },
    {
      id: '12',
      image: '12.webp',
      company: 'US POLO',
      item_name: 'Shirt for Men',
      original_price: 799,
      current_price: 799,
      discount_percentage: 0,
      return_period: 10,
      delivery_date: '10 Sep 2025',
      rating:{
        stars: 3.9,
        count: 4567,
      },
    },
    {
      id: '13',
      image: '13.webp',
      company: 'US POLO',
      item_name: 'Shirt for Women',
      original_price: 699,
      current_price: 699,
      discount_percentage: 0,
      return_period: 10,
      delivery_date: '10 Sep 2025',
      rating:{
        stars: 2.9,
        count: 2546,
      },
    },
    {
      id: '14',
      image: '14.webp',
      company: 'H&M',
      item_name: 'Half Sleeves Shirt for Women',
      original_price: 599,
      current_price:5199,
      discount_percentage: 0,
      return_period: 10,
      delivery_date: '10 Sep 2025',
      rating:{
        stars: 3.9,
        count: 4567,
      },
    },
    {
      id: '15',
      image: '15.jpg',
      company: 'KIDS',
      item_name: 'Male Doll',
      original_price: 799,
      current_price: 799,
      discount_percentage: 0,
      return_period: 10,
      delivery_date: '10 Sep 2025',
      rating:{
        stars: 4.9,
        count: 9874,
      },
    },
    {
      id: '16',
      image: '16.jpg',
      company: 'AS TOYS',
      item_name: 'Car for Kids',
      original_price: 1499,
      current_price: 1499,
      discount_percentage: 0,
      return_period: 10,
      delivery_date: '10 Sep 2025',
      rating:{
        stars: 3.9,
        count: 4556,
      },
    },
  ]; 